openapi: 3.0.0
info:
  title: MemberComm
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  client/communication/unreadcount:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseEntity'
              examples:
                example-1:
                  value:
                    status: success/warn/error
                    status_message: Successfully retrived count
                    data:
                      claimantid: ''
                      unreadcount: ''
      operationId: get-communication-unreadcount
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            examples:
              example-1:
                value:
                  status: success/warn/error
                  status_message: Successfully retrived count
                  data:
                    claimantid: ''
                    unreadcount: ''
        description: ''
      description: To get Unread count
      parameters:
        - schema:
            type: string
          in: query
          name: claimantid
          description: Claimant ID
    parameters: []
  client/communication/unreadcount/all:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseEntity'
              examples:
                example-1:
                  value:
                    status: success/warn/error
                    status_message: Successfully retrived all the claims count
                    data:
                      - cliamId: NNTN-01
                        unreadcount: '23'
                      - cliamId: NNTN-01
                        unreadcount: '12'
                      - cliamId: NNTN-01
                        unreadcount: '3'
                      - cliamId: NNTN-01
                        unreadcount: '32'
                      - cliamId: NNTN-01
                        unreadcount: '1'
      operationId: get-communication-unreadcount-all
      description: Get all unread count of Cliam
      parameters:
        - schema:
            type: string
          in: query
          name: claimantid
          description: Climant ID
    parameters: []
  client/communication/summary:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                example-1:
                  value:
                    status: success/warn/error
                    status_message: Successfully retrived all the Summary detail
                    data:
                      claimantid: ''
                      claimid: ''
                      totalRead: 2
                      totalUnread: 1
                      communications:
                        - communicationId: '001'
                          status: READ
                          subject: ''
                          text: ''
                          initialLines: claims sumbitted
                          datetimesent: ''
                          type: 'email, text, pdf'
                          filenetId: '123456'
                        - communicationId: '002'
                          status: UNREAD
                          subject: ''
                          text: ''
                          initialLines: claims sumbitted
                          datetimesent: ''
                          type: 'email, text, pdf'
                          filenetId: '123456'
      operationId: get-client-communication-summary
      description: To get Summary
      parameters:
        - schema:
            type: string
          in: query
          name: claimanantid
          description: Claimant ID
        - schema:
            type: string
          in: query
          name: claimid
          description: Claim ID
    parameters: []
  client/communication/detail/:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-rest-api-v1-client-communication-detail
      description: To get communication detail
      parameters:
        - schema:
            type: string
          in: query
          name: type
          description: Communication type pdf/message/email
        - schema:
            type: string
          in: query
          name: commid
          description: Communication ID
        - schema:
            type: string
          in: query
          name: filenetid
          description: Filenet ID
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResponseEntity'
            examples:
              example-1:
                value:
                  status: success/warn/error
                  status_message: Successfully retrived all the Summary detail
                  data:
                    documentName: Claim received
                    byteArray: ''
              example-2:
                value:
                  status: success/warn/error
                  status_message: Successfully retrived all the Summary detail
                  data:
                    emailSubject: Claim received
                    emailReceivedTime: ''
                    emailContent: html String
    parameters: []
  client/communication/readmessage:
    put:
      summary: ''
      operationId: put-client-communication-readmessage
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseEntity'
              examples:
                example-1:
                  value:
                    status: success/warn/error
                    status_message: Successfully updated communication status
                    data: {}
      parameters:
        - schema:
            type: string
          in: query
          name: claimantid
          description: Claimant ID
        - schema:
            type: string
          in: query
          name: claimid
          description: Claim ID
        - schema:
            type: string
          in: query
          name: commid
          description: Communication ID
      description: To update communication status read/unread
    parameters: []
  /client/communication/claimantid:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-client-communication-claimantid
      parameters:
        - schema:
            type: string
          in: query
          name: memberid
          description: Member ID
      description: To get GCS cliamant id based on Member id
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            examples:
              example-1:
                value:
                  status: success/warn/error
                  status_message: Successfully retrived count
                  data:
                    gcsclaimantid: ''
        description: ''
components:
  schemas:
    ResponseEntity:
      title: ResponseEntity
      x-examples:
        example-1:
          status: string
          statusmessage: string
          data: null
      type: object
      description: ''
      properties:
        status:
          type: string
        statusMessage:
          type: string
        data:
          anyOf: []
        ErrorMessage:
          allOf: []
